"""
LLM enrichment script v0.

Calls Claude with prompt caching on the (large, static) system prompt.
Returns structured EnrichmentResult via tool_use — no free-text parsing.

TODO (Eric): fill in SYSTEM_PROMPT with your clinical context/guidelines.
"""

from __future__ import annotations

import json
import os
from typing import Union

import anthropic
from dotenv import load_dotenv

from ai_layer.models import (
    CategoryScore,
    ConditionRecord,
    EnrichmentResult,
    MedicationRecord,
)

load_dotenv()

_client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

MODEL = "claude-sonnet-4-6"

# ---------------------------------------------------------------------------
# TODO (Eric): write your clinical system prompt here.
# Keep it substantial (>1024 tokens) to get prompt cache hits.
# Include: clinical coding standards (ICD-10, NDC), scoring rubric,
# what each of your 6 categories means, and output expectations.
# ---------------------------------------------------------------------------
SYSTEM_PROMPT = """
You are a clinical data enrichment specialist evaluating synthetic EHR records
generated by Synthea from a FHIR R4 dataset. Your task is to assess each
record — either a condition or a medication — across 6 clinical quality
dimensions and return a structured confidence score (0.0–1.0) for each.

Records come from a patient population with chronic and acute conditions
including Type 2 Diabetes (T2D), Chronic Kidney Disease (CKD), hypertension,
obesity, asthma, and common comorbidity clusters seen in real-world claims data.
Medications include first-line therapies (metformin, lisinopril, atorvastatin),
inhalers, and common polypharmacy combinations.

## Universal Scoring Scale

Apply this scale consistently across all 6 categories:

  0.0 – 0.2  Very low: record is missing key fields, code is completely
              non-specific (e.g. Z99, R69), or description contradicts the code.

  0.3 – 0.4  Low: partial information present; code is a 3-character catch-all
              with no further specification; clinical rationale is weak.

  0.5 – 0.6  Moderate: code is valid and description broadly matches, but
              specificity is limited — could apply to a wide patient population.

  0.7 – 0.8  High: code is specific (5–7 characters for ICD-10, full NDC for
              medications), description matches code, clinical context is clear.

  0.9 – 1.0  Definitive: textbook-quality record. ICD-10 at maximum specificity,
              description exactly matches code intent, no ambiguity.

## Category Definitions and Scoring Rubrics

### 1. diagnosis_specificity
Measures how specific the ICD-10 code is. ICD-10 codes range from 3 characters
(category level, e.g. E11 — Type 2 diabetes) to 7 characters (full specificity,
e.g. E11.65 — T2D with hyperglycemia). More characters = more specificity.

  Score 0.9–1.0: 5–7 character code; description matches exactly.
  Score 0.7–0.8: 4–5 character code; description is clinically coherent.
  Score 0.5–0.6: 3–4 character code (category-level); still valid but not specific.
  Score 0.2–0.4: Code is a catch-all (e.g. R69 — illness unspecified, Z99).
  Score 0.0–0.1: Code missing, invalid format, or description is blank.

For medication records, score based on NDC specificity:
  full 11-digit NDC = 0.9+; partial or missing NDC = lower.

### 2. clinical_urgency
Measures implied acuity — how urgent or severe is this record?

  Score 0.9–1.0: Acute, life-threatening, or high-severity condition/medication.
                 Examples: sepsis, acute MI (I21.x), insulin for DKA,
                 vasopressors, emergency bronchodilators.
  Score 0.7–0.8: Subacute or significant chronic disease with known complication
                 risk. Examples: uncontrolled hypertension, CKD stage 3+,
                 T2D with complications (E11.4x, E11.6x).
  Score 0.5–0.6: Stable chronic condition managed with routine medication.
                 Examples: well-controlled T2D (E11.9), mild persistent asthma.
  Score 0.3–0.4: Low-acuity or preventive record. Examples: wellness visit
                 medications, vitamin supplements, screening diagnoses.
  Score 0.0–0.2: No clinical urgency signal detectable from the record.

For conditions, also consider onset_date recency: a recent onset date on an
acute code raises urgency; a decades-old onset on a chronic code lowers it.

### 3. coding_accuracy
Measures whether the description text matches what the ICD-10 or NDC code
actually represents. This catches mismatches between free-text and coded values.

  Score 0.9–1.0: Description is the official ICD-10 or NDC label, or is a
                 direct clinical synonym. No discrepancy.
  Score 0.7–0.8: Minor wording difference but clinically equivalent.
  Score 0.5–0.6: Description is related but broader or narrower than the code.
  Score 0.3–0.4: Partial mismatch — description suggests a different condition
                 or medication than the code.
  Score 0.0–0.2: Clear mismatch — description and code are clinically unrelated,
                 or description is empty/generic ("condition", "medication").

### 4. medication_appropriateness
Measures whether this medication is clinically reasonable in isolation or given
the patient context available. This does not require a confirmed condition match —
score on the medication's general clinical profile.

  Score 0.9–1.0: First-line, guideline-recommended medication. Examples:
                 metformin for T2D, ACE inhibitor for hypertension, statin for
                 hyperlipidemia, albuterol for asthma.
  Score 0.7–0.8: Second-line or adjunct therapy with clear clinical indication.
  Score 0.5–0.6: Medication is clinically valid but indication is unclear from
                 the record alone.
  Score 0.3–0.4: Off-label use possible but not well-supported by the record.
  Score 0.0–0.2: Medication appears clinically inappropriate or record is missing
                 enough information to assess.

For condition records (not medications), score this category 0.5 as neutral —
conditions are not medications and this dimension does not directly apply.

### 5. drug_condition_alignment
Measures whether a recognized, evidence-based drug-condition pair can be
inferred from this record and the broader patient context.

  Score 0.9–1.0: Textbook pair. Examples: metformin + T2D, lisinopril +
                 hypertension or CKD, atorvastatin + hyperlipidemia,
                 albuterol + asthma, levothyroxine + hypothyroidism.
  Score 0.7–0.8: Plausible pair, not always first-line but clinically supported.
  Score 0.5–0.6: Indirect alignment — medication treats a complication or
                 comorbidity of the condition, not the condition itself.
  Score 0.3–0.4: Weak or speculative alignment.
  Score 0.0–0.2: No recognizable drug-condition relationship, or condition record
                 with no medication context to align to.

For standalone condition records without medication context, score 0.4 unless
the condition strongly implies a standard medication (e.g. T2D → metformin likely).

### 6. comorbidity_risk
Measures whether this record signals elevated multi-condition risk — a patient
likely has or will develop additional conditions that compound clinical complexity.

  Score 0.9–1.0: Record is part of a high-risk comorbidity cluster with known
                 clinical progression. Examples: T2D + CKD (diabetic nephropathy
                 pathway), obesity + hypertension + T2D (metabolic syndrome),
                 heart failure + CKD (cardiorenal syndrome).
  Score 0.7–0.8: Single condition with well-known comorbidity associations.
                 Examples: T2D alone, hypertension alone, obesity (BMI 35+).
  Score 0.5–0.6: Moderate-risk condition with some comorbidity associations
                 but not a primary comorbidity driver.
  Score 0.3–0.4: Low comorbidity signal — acute or isolated condition unlikely
                 to drive multi-condition patterns.
  Score 0.0–0.2: No meaningful comorbidity risk signal in this record.

## Output Rules

- Always call the submit_enrichment tool. Never respond in free text.
- Score all 6 categories even if a category is less applicable to the record
  type — use the neutral scoring guidance in each rubric above.
- overall_confidence: compute as a weighted average where diagnosis_specificity
  and coding_accuracy are weighted 1.5x, all others 1x. Round to 2 decimal places.
- rationale: exactly one sentence per category. Cite the specific code, keyword,
  or clinical pattern that drove the score. Be concrete, not generic.
- If the record description is lowercase (Synthea outputs lowercase), treat it
  as equivalent to the properly-cased clinical term.
"""

# ---------------------------------------------------------------------------
# Tool definition — Claude uses tool_use to return structured output.
# TODO (Eric): rename category_1..6 to your actual category names.
#              Update each "description" field with clinical meaning.
# ---------------------------------------------------------------------------
ENRICHMENT_TOOL: dict = {
    "name": "submit_enrichment",
    "description": (
        # TODO: describe what the tool does in clinical terms
        "Submit structured clinical enrichment scores for a medical record."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "diagnosis_specificity": {
                "type": "object",
                "description": "Is the ICD-10 code specific (7-char) or a catch-all (3-char)?",
                "properties": {
                    "score": {"type": "number", "minimum": 0, "maximum": 1},
                    "rationale": {"type": "string"},
                },
                "required": ["score", "rationale"],
            },
            "clinical_urgency": {
                "type": "object",
                "description": "Acuity signal — acute vs. chronic, severity implied by the record.",
                "properties": {
                    "score": {"type": "number", "minimum": 0, "maximum": 1},
                    "rationale": {"type": "string"},
                },
                "required": ["score", "rationale"],
            },
            "coding_accuracy": {
                "type": "object",
                "description": "Does the description match the ICD-10 or NDC code?",
                "properties": {
                    "score": {"type": "number", "minimum": 0, "maximum": 1},
                    "rationale": {"type": "string"},
                },
                "required": ["score", "rationale"],
            },
            "medication_appropriateness": {
                "type": "object",
                "description": "Is this medication clinically reasonable given the record context?",
                "properties": {
                    "score": {"type": "number", "minimum": 0, "maximum": 1},
                    "rationale": {"type": "string"},
                },
                "required": ["score", "rationale"],
            },
            "drug_condition_alignment": {
                "type": "object",
                "description": "Does a recognized drug-condition pair exist for this record?",
                "properties": {
                    "score": {"type": "number", "minimum": 0, "maximum": 1},
                    "rationale": {"type": "string"},
                },
                "required": ["score", "rationale"],
            },
            "comorbidity_risk": {
                "type": "object",
                "description": "Does this record signal elevated multi-condition risk?",
                "properties": {
                    "score": {"type": "number", "minimum": 0, "maximum": 1},
                    "rationale": {"type": "string"},
                },
                "required": ["score", "rationale"],
            },
            "overall_confidence": {
                "type": "number",
                "minimum": 0,
                "maximum": 1,
                "description": "Weighted overall confidence across all 6 categories.",
            },
        },
        "required": [
            "diagnosis_specificity", "clinical_urgency", "coding_accuracy",
            "medication_appropriateness", "drug_condition_alignment", "comorbidity_risk",
            "overall_confidence",
        ],
    },
}


def _build_user_message(record: Union[ConditionRecord, MedicationRecord]) -> str:
    """Format a staging record into the user turn.

    TODO (Eric): expand this to include any additional context you want
    Claude to see (e.g. patient age from stg_person join, co-occurring
    conditions/medications for the same patient_id).
    """
    if isinstance(record, ConditionRecord):
        return (
            f"Record type: CONDITION\n"
            f"Patient ID: {record.patient_id}\n"
            f"Code: {record.condition_code}\n"
            f"Description: {record.condition_description}\n"
            f"Onset date: {record.onset_date or 'unknown'}\n\n"
            f"Score this condition record across all 6 clinical categories."
        )
    return (
        f"Record type: MEDICATION\n"
        f"Patient ID: {record.patient_id}\n"
        f"Code: {record.medication_code}\n"
        f"Description: {record.medication_description}\n"
        f"Start date: {record.start_date or 'unknown'}\n\n"
        f"Score this medication record across all 6 clinical categories."
    )


def enrich_record(
    record: Union[ConditionRecord, MedicationRecord],
) -> EnrichmentResult:
    """Call Claude to enrich a single condition or medication record.

    Uses prompt caching on the system prompt (static clinical context).
    Returns a validated EnrichmentResult — raises on tool_use failure.
    """
    response = _client.messages.create(
        model=MODEL,
        max_tokens=1024,
        system=[
            {
                "type": "text",
                "text": SYSTEM_PROMPT,
                "cache_control": {"type": "ephemeral"},  # cache the large system prompt
            }
        ],
        tools=[ENRICHMENT_TOOL],
        tool_choice={"type": "tool", "name": "submit_enrichment"},
        messages=[
            {"role": "user", "content": _build_user_message(record)},
        ],
    )

    tool_block = next(
        (b for b in response.content if b.type == "tool_use"), None
    )
    if tool_block is None:
        raise RuntimeError(
            f"Claude did not return a tool_use block for {record}. "
            f"Stop reason: {response.stop_reason}"
        )

    raw: dict = tool_block.input

    record_code = (
        record.condition_code
        if isinstance(record, ConditionRecord)
        else record.medication_code
    )
    record_description = (
        record.condition_description
        if isinstance(record, ConditionRecord)
        else record.medication_description
    )
    record_type = "condition" if isinstance(record, ConditionRecord) else "medication"

    return EnrichmentResult(
        patient_id=record.patient_id,
        record_type=record_type,
        record_code=record_code,
        record_description=record_description,
        diagnosis_specificity=CategoryScore(**raw["diagnosis_specificity"]),
        clinical_urgency=CategoryScore(**raw["clinical_urgency"]),
        coding_accuracy=CategoryScore(**raw["coding_accuracy"]),
        medication_appropriateness=CategoryScore(**raw["medication_appropriateness"]),
        drug_condition_alignment=CategoryScore(**raw["drug_condition_alignment"]),
        comorbidity_risk=CategoryScore(**raw["comorbidity_risk"]),
        overall_confidence=raw["overall_confidence"],
    )


def enrich_batch(
    records: list[Union[ConditionRecord, MedicationRecord]],
    *,
    stop_on_error: bool = False,
) -> tuple[list[EnrichmentResult], list[dict]]:
    """Enrich a list of records. Returns (results, errors).

    Prompt cache warms on the first call; subsequent calls in the same
    batch hit the cache and cost ~10% of the input token price.
    """
    results: list[EnrichmentResult] = []
    errors: list[dict] = []

    for record in records:
        try:
            results.append(enrich_record(record))
        except Exception as exc:
            err = {
                "patient_id": record.patient_id,
                "record_code": getattr(record, "condition_code", None)
                or getattr(record, "medication_code", None),
                "error": str(exc),
            }
            errors.append(err)
            if stop_on_error:
                raise

    return results, errors
