"""
LLM enrichment layer.

Scores each FHIR record across 6 clinical quality dimensions using tool_use
structured output and prompt caching. Concurrent batch processing via
ThreadPoolExecutor. Returns per-call token usage and aggregated cost.
"""

from __future__ import annotations

import os
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Union

import anthropic
from dotenv import load_dotenv

from ai_layer.models import (
    CategoryScore,
    ConditionRecord,
    EnrichmentResult,
    MedicationRecord,
)

load_dotenv()

_client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

MODEL = "claude-sonnet-4-6"

# ---------------------------------------------------------------------------
# System prompt — SNOMED CT / RxNorm aware, >1024 tokens for cache hits.
# ---------------------------------------------------------------------------
SYSTEM_PROMPT = """
You are a clinical data enrichment specialist evaluating synthetic EHR records
generated by Synthea from a FHIR R4 dataset. Your task is to assess each
record — either a condition or a medication — across 6 clinical quality
dimensions and return a structured confidence score (0.0–1.0) for each.

Records come from a patient population with chronic and acute conditions
including Type 2 Diabetes (T2D), Chronic Kidney Disease (CKD), hypertension,
obesity, asthma, and common comorbidity clusters seen in real-world claims data.
Medications include first-line therapies (metformin, lisinopril, atorvastatin),
inhalers, and common polypharmacy combinations.

## Code Systems in This Dataset

CONDITION records use SNOMED CT codes (numeric, e.g. 44054006 = "Type 2 diabetes
mellitus"). SNOMED CT specificity is measured by concept granularity — how
specific the clinical concept is, not code length.

MEDICATION records use RxNorm codes (numeric, e.g. 860975 = metformin 500mg).
RxNorm specificity is measured by how precisely the code identifies the drug,
dose, and form. A clinical drug code (with dose + form) is more specific than
an ingredient-only code.

Do NOT apply ICD-10 character-length rules to SNOMED CT codes. Do NOT apply
NDC rules to RxNorm codes. Score specificity based on concept granularity.

## Universal Scoring Scale

Apply this scale consistently across all 6 categories:

  0.0 – 0.2  Very low: record is missing key fields, code is completely
              non-specific, or description contradicts the code.

  0.3 – 0.4  Low: partial information present; code is a broad category-level
              concept; clinical rationale is weak.

  0.5 – 0.6  Moderate: code is valid and description broadly matches, but
              specificity is limited — could apply to a wide patient population.

  0.7 – 0.8  High: code identifies a specific clinical concept; description
              matches code; clinical context is clear.

  0.9 – 1.0  Definitive: textbook-quality record. Highly specific concept with
              exact description match; no ambiguity.

## Category Definitions and Scoring Rubrics

### 1. diagnosis_specificity
For CONDITION records (SNOMED CT): measures how specific the clinical concept is.
  Score 0.9–1.0: Leaf-level or near-leaf SNOMED concept. Description names a
                 specific disorder with qualifiers (e.g. "Type 2 diabetes mellitus
                 with diabetic nephropathy", "Acute ST-elevation myocardial infarction
                 of anterior wall"). No ambiguity about the clinical entity.
  Score 0.7–0.8: Specific condition with a clear clinical identity but no
                 complication qualifier (e.g. "Type 2 diabetes mellitus",
                 "Essential hypertension", "Chronic kidney disease stage 3").
  Score 0.5–0.6: Moderately specific — identifies a condition category but lacks
                 granularity (e.g. "Chronic kidney disease", "Asthma").
  Score 0.3–0.4: Broad, category-level concept (e.g. "Disorder of kidney",
                 "Finding of glucose level").
  Score 0.0–0.2: Generic, non-specific, or a finding code with no clinical
                 identity (e.g. "Stress (finding)", "Abnormal result").

For MEDICATION records (RxNorm): measures drug-dose-form specificity.
  Score 0.9–1.0: Clinical drug code with specific dose + form (e.g. "Metformin
                 500 MG Oral Tablet").
  Score 0.7–0.8: Ingredient + form but no specific dose (e.g. "Metformin
                 Oral Tablet").
  Score 0.5–0.6: Ingredient only (e.g. "Metformin").
  Score 0.2–0.4: Missing, ambiguous, or unrecognized RxNorm code.

### 2. clinical_urgency
Measures implied acuity — how urgent or severe is this record?

  Score 0.9–1.0: Acute, life-threatening, or high-severity condition/medication.
                 Examples: sepsis, acute MI (I21.x), insulin for DKA,
                 vasopressors, emergency bronchodilators.
  Score 0.7–0.8: Subacute or significant chronic disease with known complication
                 risk. Examples: uncontrolled hypertension, CKD stage 3+,
                 T2D with complications (E11.4x, E11.6x).
  Score 0.5–0.6: Stable chronic condition managed with routine medication.
                 Examples: well-controlled T2D (E11.9), mild persistent asthma.
  Score 0.3–0.4: Low-acuity or preventive record. Examples: wellness visit
                 medications, vitamin supplements, screening diagnoses.
  Score 0.0–0.2: No clinical urgency signal detectable from the record.

For conditions, also consider onset_date recency: a recent onset date on an
acute code raises urgency; a decades-old onset on a chronic code lowers it.

### 3. coding_accuracy
Measures whether the description text matches what the ICD-10 or NDC code
actually represents. This catches mismatches between free-text and coded values.

  Score 0.9–1.0: Description is the official ICD-10 or NDC label, or is a
                 direct clinical synonym. No discrepancy.
  Score 0.7–0.8: Minor wording difference but clinically equivalent.
  Score 0.5–0.6: Description is related but broader or narrower than the code.
  Score 0.3–0.4: Partial mismatch — description suggests a different condition
                 or medication than the code.
  Score 0.0–0.2: Clear mismatch — description and code are clinically unrelated,
                 or description is empty/generic ("condition", "medication").

### 4. medication_appropriateness
Measures whether this medication is clinically reasonable in isolation or given
the patient context available. This does not require a confirmed condition match —
score on the medication's general clinical profile.

  Score 0.9–1.0: First-line, guideline-recommended medication. Examples:
                 metformin for T2D, ACE inhibitor for hypertension, statin for
                 hyperlipidemia, albuterol for asthma.
  Score 0.7–0.8: Second-line or adjunct therapy with clear clinical indication.
  Score 0.5–0.6: Medication is clinically valid but indication is unclear from
                 the record alone.
  Score 0.3–0.4: Off-label use possible but not well-supported by the record.
  Score 0.0–0.2: Medication appears clinically inappropriate or record is missing
                 enough information to assess.

For condition records (not medications), score this category 0.5 as neutral —
conditions are not medications and this dimension does not directly apply.

### 5. drug_condition_alignment
Measures whether a recognized, evidence-based drug-condition pair can be
inferred from this record and the broader patient context.

  Score 0.9–1.0: Textbook pair. Examples: metformin + T2D, lisinopril +
                 hypertension or CKD, atorvastatin + hyperlipidemia,
                 albuterol + asthma, levothyroxine + hypothyroidism.
  Score 0.7–0.8: Plausible pair, not always first-line but clinically supported.
  Score 0.5–0.6: Indirect alignment — medication treats a complication or
                 comorbidity of the condition, not the condition itself.
  Score 0.3–0.4: Weak or speculative alignment.
  Score 0.0–0.2: No recognizable drug-condition relationship, or condition record
                 with no medication context to align to.

For standalone condition records without medication context, score 0.4 unless
the condition strongly implies a standard medication (e.g. T2D → metformin likely).

### 6. comorbidity_risk
Measures whether this record signals elevated multi-condition risk — a patient
likely has or will develop additional conditions that compound clinical complexity.

  Score 0.9–1.0: Record is part of a high-risk comorbidity cluster with known
                 clinical progression. Examples: T2D + CKD (diabetic nephropathy
                 pathway), obesity + hypertension + T2D (metabolic syndrome),
                 heart failure + CKD (cardiorenal syndrome).
  Score 0.7–0.8: Single condition with well-known comorbidity associations.
                 Examples: T2D alone, hypertension alone, obesity (BMI 35+).
  Score 0.5–0.6: Moderate-risk condition with some comorbidity associations
                 but not a primary comorbidity driver.
  Score 0.3–0.4: Low comorbidity signal — acute or isolated condition unlikely
                 to drive multi-condition patterns.
  Score 0.0–0.2: No meaningful comorbidity risk signal in this record.

## Output Rules

- Always call the submit_enrichment tool. Never respond in free text.
- Score all 6 categories even if a category is less applicable to the record
  type — use the neutral scoring guidance in each rubric above.
- overall_confidence: compute as a weighted average where diagnosis_specificity
  and coding_accuracy are weighted 1.5x, all others 1x. Round to 2 decimal places.
- rationale: exactly one sentence per category. Cite the specific code, keyword,
  or clinical pattern that drove the score. Be concrete, not generic.
- If the record description is lowercase (Synthea outputs lowercase), treat it
  as equivalent to the properly-cased clinical term.
"""

# ---------------------------------------------------------------------------
# Tool definition — enforces structured output via tool_use.
# ---------------------------------------------------------------------------
ENRICHMENT_TOOL: dict = {
    "name": "submit_enrichment",
    "description": "Submit structured clinical enrichment scores for a FHIR EHR record.",
    "input_schema": {
        "type": "object",
        "properties": {
            "diagnosis_specificity": {
                "type": "object",
                "description": "Is the ICD-10 code specific (7-char) or a catch-all (3-char)?",
                "properties": {
                    "score": {"type": "number", "minimum": 0, "maximum": 1},
                    "rationale": {"type": "string"},
                },
                "required": ["score", "rationale"],
            },
            "clinical_urgency": {
                "type": "object",
                "description": "Acuity signal — acute vs. chronic, severity implied by the record.",
                "properties": {
                    "score": {"type": "number", "minimum": 0, "maximum": 1},
                    "rationale": {"type": "string"},
                },
                "required": ["score", "rationale"],
            },
            "coding_accuracy": {
                "type": "object",
                "description": "Does the description match the ICD-10 or NDC code?",
                "properties": {
                    "score": {"type": "number", "minimum": 0, "maximum": 1},
                    "rationale": {"type": "string"},
                },
                "required": ["score", "rationale"],
            },
            "medication_appropriateness": {
                "type": "object",
                "description": "Is this medication clinically reasonable given the record context?",
                "properties": {
                    "score": {"type": "number", "minimum": 0, "maximum": 1},
                    "rationale": {"type": "string"},
                },
                "required": ["score", "rationale"],
            },
            "drug_condition_alignment": {
                "type": "object",
                "description": "Does a recognized drug-condition pair exist for this record?",
                "properties": {
                    "score": {"type": "number", "minimum": 0, "maximum": 1},
                    "rationale": {"type": "string"},
                },
                "required": ["score", "rationale"],
            },
            "comorbidity_risk": {
                "type": "object",
                "description": "Does this record signal elevated multi-condition risk?",
                "properties": {
                    "score": {"type": "number", "minimum": 0, "maximum": 1},
                    "rationale": {"type": "string"},
                },
                "required": ["score", "rationale"],
            },
            "overall_confidence": {
                "type": "number",
                "minimum": 0,
                "maximum": 1,
                "description": "Weighted overall confidence across all 6 categories.",
            },
        },
        "required": [
            "diagnosis_specificity", "clinical_urgency", "coding_accuracy",
            "medication_appropriateness", "drug_condition_alignment", "comorbidity_risk",
            "overall_confidence",
        ],
    },
}


def _build_user_message(
    record: Union[ConditionRecord, MedicationRecord],
    patient_context: dict | None = None,
) -> str:
    """Format a staging record into the user turn, optionally with patient context."""
    if isinstance(record, ConditionRecord):
        lines = [
            "Record type: CONDITION (code system: SNOMED CT)",
            f"Patient ID: {record.patient_id}",
            f"Code: {record.condition_code}",
            f"Description: {record.condition_description}",
            f"Onset date: {record.onset_date or 'unknown'}",
        ]
    else:
        lines = [
            "Record type: MEDICATION (code system: RxNorm)",
            f"Patient ID: {record.patient_id}",
            f"Code: {record.medication_code}",
            f"Description: {record.medication_description}",
            f"Start date: {record.start_date or 'unknown'}",
        ]

    if patient_context:
        other_conditions = patient_context.get("conditions", [])
        other_medications = patient_context.get("medications", [])
        if other_conditions or other_medications:
            lines.append("\nPatient context (co-occurring records for this patient):")
        if other_conditions:
            lines.append("  Other conditions:")
            for c in other_conditions[:5]:
                lines.append(f"    - {c['code']}: {c['description']}")
        if other_medications:
            lines.append("  Other medications:")
            for m in other_medications[:5]:
                lines.append(f"    - {m['code']}: {m['description']}")

    lines.append("\nScore this record across all 6 clinical categories.")
    return "\n".join(lines)


# Sonnet pricing per token (USD)
_INPUT_COST = 3.0 / 1_000_000
_OUTPUT_COST = 15.0 / 1_000_000
_CACHE_READ_COST = 0.30 / 1_000_000
_CACHE_WRITE_COST = 3.75 / 1_000_000


def enrich_record(
    record: Union[ConditionRecord, MedicationRecord],
    patient_context: dict | None = None,
) -> tuple[EnrichmentResult, dict]:
    """Call Claude to enrich a single record. Returns (EnrichmentResult, usage_dict).

    Uses prompt caching on the system prompt (static clinical context).
    Raises on tool_use failure.
    """
    response = _client.messages.create(
        model=MODEL,
        max_tokens=1024,
        system=[
            {
                "type": "text",
                "text": SYSTEM_PROMPT,
                "cache_control": {"type": "ephemeral"},
            }
        ],
        tools=[ENRICHMENT_TOOL],
        tool_choice={"type": "tool", "name": "submit_enrichment"},
        messages=[
            {"role": "user", "content": _build_user_message(record, patient_context)},
        ],
    )

    tool_block = next(
        (b for b in response.content if b.type == "tool_use"), None
    )
    if tool_block is None:
        raise RuntimeError(
            f"Claude did not return a tool_use block for {record}. "
            f"Stop reason: {response.stop_reason}"
        )

    raw: dict = tool_block.input
    u = response.usage
    input_tokens = u.input_tokens
    output_tokens = u.output_tokens
    cache_read = getattr(u, "cache_read_input_tokens", 0) or 0
    cache_write = getattr(u, "cache_creation_input_tokens", 0) or 0
    cost_usd = (
        input_tokens * _INPUT_COST
        + output_tokens * _OUTPUT_COST
        + cache_read * _CACHE_READ_COST
        + cache_write * _CACHE_WRITE_COST
    )
    usage = {
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "cache_read_tokens": cache_read,
        "cache_write_tokens": cache_write,
        "cost_usd": cost_usd,
    }

    record_code = (
        record.condition_code
        if isinstance(record, ConditionRecord)
        else record.medication_code
    )
    record_description = (
        record.condition_description
        if isinstance(record, ConditionRecord)
        else record.medication_description
    )
    record_type = "condition" if isinstance(record, ConditionRecord) else "medication"

    result = EnrichmentResult(
        patient_id=record.patient_id,
        record_type=record_type,
        record_code=record_code,
        record_description=record_description,
        diagnosis_specificity=CategoryScore(**raw["diagnosis_specificity"]),
        clinical_urgency=CategoryScore(**raw["clinical_urgency"]),
        coding_accuracy=CategoryScore(**raw["coding_accuracy"]),
        medication_appropriateness=CategoryScore(**raw["medication_appropriateness"]),
        drug_condition_alignment=CategoryScore(**raw["drug_condition_alignment"]),
        comorbidity_risk=CategoryScore(**raw["comorbidity_risk"]),
        overall_confidence=raw["overall_confidence"],
    )
    return result, usage


def enrich_batch(
    records: list[Union[ConditionRecord, MedicationRecord]],
    *,
    patient_context: dict | None = None,
    stop_on_error: bool = False,
    max_workers: int = 10,
) -> tuple[list[EnrichmentResult], list[dict], dict]:
    """Enrich a list of records concurrently. Returns (results, errors, usage).

    patient_context: optional dict[patient_id -> {conditions, medications}]
    usage: aggregated token counts and cost_usd across all calls.
    """
    results: list[EnrichmentResult] = []
    errors: list[dict] = []
    agg = {"input_tokens": 0, "output_tokens": 0, "cache_read_tokens": 0, "cache_write_tokens": 0, "cost_usd": 0.0}

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        future_to_record = {
            executor.submit(
                enrich_record,
                r,
                patient_context.get(r.patient_id) if patient_context else None,
            ): r
            for r in records
        }
        for future in as_completed(future_to_record):
            record = future_to_record[future]
            try:
                result, usage = future.result()
                results.append(result)
                for k in agg:
                    agg[k] += usage[k]
            except Exception as exc:
                err = {
                    "patient_id": record.patient_id,
                    "record_code": getattr(record, "condition_code", None)
                    or getattr(record, "medication_code", None),
                    "error": str(exc),
                }
                errors.append(err)
                if stop_on_error:
                    raise

    return results, errors, agg
